# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 09:08
from __future__ import unicode_literals

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rand_num',
            field=models.IntegerField(default=apps.accounts.models.get_rand_num),
        ),
    ]
